- package.json
- public/css/draw.css
- public/scripts/classes/draw.js
- server.js
- src/views/draw.html
- tests/draw.test.js
This pull request addresses User Story #10 , which focuses on creating a drawing screen for the user. The user is able to see the screen but will not be able to draw. 
Note:
> User Story #10: View a Drawing Canvas

- public/css/account.css
- public/css/lobby.css
- public/css/main.css
- server.js
- src/views/index.html
- src/views/lobby.html
- tests/lobby.test.js
This pull request addresses User Story #5, which focuses on creating a lobby screen which is a dedicated screen with joining or creating lobby options.
Note:
> User Story #5: View a Lobby Type Layout Screen.

- public/css/draw.css
- public/scripts/classes/draw.js
- src/views/draw.html
- tests/draw.test.js
This pull request addresses User Story #11 , which focuses on allowing a user to be able to draw on a canvas. The drawing for the user can only be done in one type of colour and pen size. 
Note:
> User story #11: Be able to Draw on the Canvas 

- public/scripts/classes/client.js
- public/scripts/classes/screenManager.js
- server.js
- src/views/lobby.html
- tests/lobby.test.js
Functionality to start the game when a minimum of three players have joined the same lobby.  The players have temporarily been redirected to the drawing screen as the implementation of game logic is in the third sprint. The testing was only done to ensure the start game button is visible as the implementation of starting the game will be changed. 
Note:
> User story #9: Option to Start a Same if Minimum Players have Joined 

- public/css/lobby.css
- public/css/main.css
- public/scripts/classes/client.js
- public/scripts/classes/firebase.js
- public/scripts/classes/screenManager.js
- server.js
- src/views/account.html
- src/views/index.html
- src/views/lobby.html
- tests/firebase.test.js
- tests/lobby.test.js
This pull request addresses User Story #8 (Part of Epic #15), which focuses on displaying players usernames when joining a lobby session. User Interface (UI) adjustments were made along with this Pull Request to visually enhance the displaying of usernames. I've also addressed a suggestion mentioned in Pull Request #27 where I've greyed the 'Start Game' button colour until at least 3 members have joined the lobby for which the Button colour then changes.
With regards to testing, the Playwright tests commented out initially ran and passed on my local laptop. However seem to fail when GitHub Actions attempts to run them. This will be resolved in a later sprint.
Note:
> User Story #8: See who is in the Lobby.

- public/scripts/classes/firebase.js
- server.js
- src/views/account.html
- tests/account.test.js
- tests/firebase.test.js
This pull request addresses User Story #31 , which focuses on allowing a user to add a name for their Guest Account. The input box has been added, and the username can be read. A test has been added to check if the input box can be filled.
Note:
> User story #31: Enter my name for my Guest Account

- public/scripts/classes/firebase.js
- tests/firebase.test.js
This pull request addresses User Story #32  , which focuses on allowing the user to login with a guest account. The username entered is stored in the database. A change was made to how player's are stored in the database. Each player is identified by their UID rather than their email address. A test was added to ensure guest login is successful.
Note:
> User Story #32: Login as a Guest

- package.json
- public/css/lobby.css
- public/scripts/classes/client.js
- public/scripts/classes/screenManager.js
- server.js
This pull request addresses User Story https://github.com/witseie-elen4010/2024-group-lab-001/issues/34 , which focuses on adding a count down to when the game will start. Once the start game button is pressed and there are atleast three players in a lobby, the 10 second countdown will be displayed next to the game. Once the countdown ends, the players are redirected to the drawing screen.
Note:
Tests will be completed in a future sprint once more functionality is added to lobby functionality, as this can only be tested if three players are in a lobby.
> User Story #33:  View a Countdown Initiating the Game

- public/css/draw.css
- public/scripts/classes/draw.js
- src/views/draw.html
- tests/draw.test.js
This pull request addresses User Story https://github.com/witseie-elen4010/2024-group-lab-001/issues/34 , which focuses on adding a count down to indicate how much time a player has left to draw.  Once the game starts, a player has 60 seconds to draw Once this countdown reaches zero, loses the ability to draw. A test was written to determine if the timer displays.
Note:
> User Story #34: View a Countdown When Drawing

- package.json
- public/scripts/classes/client.js
- public/scripts/classes/game.js
- socket.js
- src/views/game.html
This pull request addresses User Story #50, which allows for the core game mechanics to be completed as the first player is provided a prompt window to enter the drawing prompt they would like. This is continued by the core gameplay of broken telephone. Additional functionality such as how the game mechanics will be dealt with when a player disconnects will be done in User Story #54 including the functionality required by User Story #54.
Note:
Tests will be completed in a future sprint once functionality is completed for the game mechanics as certain functions may change. 
> User Story #50: Enter my Own Drawing Prompt

- public/scripts/classes/client.js
- public/scripts/classes/draw.js
- public/scripts/classes/game.js
- socket.js
- src/views/game.html
This pull request addresses User Story #54, which adds additional functionality to address when a player leaves the game during the game play loop. It also provides an indication to the player when it will be their turn to play and number of players turns until the end of the game. The message to the user when the drawing timer is completed has been adjusted as per the previous observation made by @MRaeesD. 
Note:
Tests will be completed in a future sprint once functionality is completed for the game mechanics as certain functions may change.
> User Story #54: Be Notified that a Player is Entering a Prompt if it is Not My Turn to Enter a Prompt 

- public/css/main.css
- public/scripts/classes/client.js
- public/scripts/classes/draw.js
- public/scripts/classes/game.js
- server.js
- socket.js
- src/views/game.html
- tests/draw.test.js
- tests/firebase.test.js
This pull request addresses User Story #56 , which allows a user to return to their current lobby session after a game has ended. Logic was added for reseting various timers within the implementation. I've also adjusted the CSS of various gameplay div containers created by @Irfaan-Mia to improve the visual experience. 
Note:
Test will be conducted on a later pull request.
> User Story #56: Option to Remain in the Same lobby and return to the Lobby Screen for a New Game

- public/css/lobby.css
- public/scripts/classes/client.js
- public/scripts/classes/game.js
- socket.js
- src/views/game.html
This pull request addresses User Story #57, which focusses on adding a countdown during initial prompting, which specifies how long a user has to input a prompt. If the timer runs out, the submit button is automatically pressed. The countdown lasts 30 seconds.
A fix was implemented so that only the host may start a game, rather than all players having this option.
Note:
Tests will be completed in a future sprint once more functionality is added to lobby functionality, as this can only be tested if three players are in a lobby.
> User Story #57: View a Countdown When Prompting

- __tests__/server.test.js
- public/scripts/classes/client.js
- public/scripts/classes/firebase.js
- server.js
- socket.js
- src/views/game.html
This pull request addresses User Story https://github.com/witseie-elen4010/2024-group-lab-001/issues/53, which focusses on providing users with a prompt by pressing a button. The user is able to randomly regenerate a prompt from a list of predefined prompts until they are satisfied with what that they are given. These prompts are stored within the database and are fetched upon request. Unit testing is done for the function that is used to randomly select prompts from the prompt list.
Note:
Additional tests will be completed in a future sprint once more functionality is added to lobby functionality, as this can only be tested if three players are in a lobby.
> User Story #53: Select a Pre-listed Prompt from a Random Set of Prompts.

- public/css/draw.css
- public/scripts/classes/draw.js
- public/scripts/classes/game.js
- src/views/draw.html
- src/views/game.html
- tests/draw.test.js
This pull request addresses User Story #74 which allows a user to change the size of the drawing tool they are using. Additionally the highlighter tool when selected has an increased pen size. A fix was also implemented to only display the start game button for the host. The CSS styling will be done by @meneerfrikkie in User Story #75. (Deleted comment from @meneerfrikkie  is the correction of the User Story number). 
Note:
> User Story #74: Select a Pen Size

- public/css/lobby.css
- public/css/main.css
- public/scripts/classes/client.js
- public/scripts/classes/game.js
- socket.js
- src/views/game.html
This pull request addresses User Story #76, which focusses on displaying all the prompts used within a game on the end game screen. Additionally, a successful implementation of identifying users in a lobby based on who is logged in was implemented. This implementation being inspired by our stakeholders request.
Note:
Please review the changes and provide any feedback or suggestions for improvement. Additionally please play the game for a few rounds to identify any potential bugs.
> User Story #76: View All Prompts

- public/scripts/classes/account.js
- src/routes/routes.js
- src/views/account.html
- src/views/admin.html
- tests/account.test.js
This pull request addresses Admin Story https://github.com/witseie-elen4010/2024-group-lab-001/issues/6 which focusses on providing admins with an option to login into an admin account.
Note:
> Admin Story #6: Select an Admin Account Option for Login

- public/scripts/classes/game.js
- src/views/game.html
This pull request addresses User Story #70 which focusses on displaying a timer when a user is guessing what has been drawn, and automatically submitting the guess once the timer runs out.
Note:
> User Story #70: View a Countdown when Guessing

- __tests__/server.test.js
- socket.js
This pull request addresses jest unit tests for User Story #33. The testing of if the start timer event is sent to the client to start the timer for initiating the start of a game. The testing of error handling for if event is sent to a non-existing roomID. The testing of the random prompts only developed in Sprint 3 was accidentally included in the previous commit. Has been removed and will be placed when doing the testing of the features from Sprint 3.
Note:
> Jest #33: View a Countdown Initiating the Game 

- public/scripts/classes/account.js
- public/scripts/classes/firebase.js
- server.js
- socket.js
- src/routes/routes.js
- src/views/account.html
- src/views/admin.html
- tests/account.test.js
This pull request addresses Admin Story https://github.com/witseie-elen4010/2024-group-lab-001/issues/26, which focusses on providing administrators access to their own unique page. On this page, admins are met with an admin display which will further be transformed to display logs in Admin Story https://github.com/witseie-elen4010/2024-group-lab-001/issues/73 . The admin is able to navigate back to account and home pages as well as being able to navigate to the game lobby screen. This page is restricted to admins, meaning that players cannot access this page. Additionally, this pull request addressed the issue of the show/hide password toggling for both password fields on the sign up page. As security measure, end-to-end tests for the admin page were not included as they required valid …
> Admin Story #26: Login as an Admin Account

- .github/workflows/playwright.yml
- tests/draw.test.js
This pull request adjusted the playwright tests to reduce flaky tests. The inclusion of the test that was initially failing on Azure is also adjusted in an attempt to get it to pass on Azure. The number of workers also for playwright tests was increased to determine if this can speed up the testing process. All tests pass locally. 
Note:
> Playwright: Draw 

- tests/lobby.test.js
This pull request adjusts the playwright tests for the lobby flows. There was flaky test which tested if three people could join a lobby and on some instances caused time outs for Webkit.  
Note:
> Playwright: Lobby

- __tests__/server.test.js
- socket.js
This pull request provides jest tests for the user stories #53 and #56. These tests cover the logic behind returning to the lobby after a game as well as the logic behind generating random prompts for a user.
Note:
Please review the tests and provide any necessary feedback.
> Jest: Select a Pre-listed Prompt from a Random Set of Prompts & Option to Remain in the Same lobby and return to the Lobby Screen for a New Game 

- tests/account.test.js
This pull request addresses the playwright tests for logging into the website. 
Note:
> Playwright: Accounts

- tests/gameplay.test.js
This pull request addresses the playwright tests for the end game screen. 
Note:
> Playwright: End-Game Screen
